[package]
name = "systest"
version = "0.1.0"
authors = ["John Schug <john.ips.schug@gmail.com>"]
publish = false

[build-dependencies]
ctest = "0.1"

[dependencies]
libc = "0.2"
libgcrypt-sys = { path = "../libgcrypt-sys" }
