[package]
name = "libgcrypt-sys"
description = "Raw bindings for libgcrypt"
repository = "https://github.com/johnschug/rust-gcrypt"
version = "0.2.0"
authors = ["John Schug <john.ips.schug@gmail.com>"]
license = "LGPL-2.1"
keywords = ["crypto", "cryptography"]
links = "gcrypt"
build = "build.rs"

[lib]
name = "libgcrypt_sys"
path = "lib.rs"

[features]
shim = ["gcc"]

[build-dependencies.gcc]
version = "0.3"
optional = true

[dependencies]
libc = "0.2"
libgpg-error-sys = "*"
