[package]
name = "libgcrypt-sys"
version = "0.5.1"
authors = ["John Schug <john.ips.schug@gmail.com>"]
repository = "https://github.com/johnschug/rust-gcrypt"
license = "LGPL-2.1"
keywords = ["crypto", "cryptography"]
categories = ["cryptography", "external-ffi-bindings"]
description = "Raw bindings for libgcrypt"
links = "gcrypt"
build = "build.rs"

[badges]
travis-ci = { repository = "johnschug/rust-gcrypt" }
appveyor = { repository = "johnschug/rust-gcrypt" }

[lib]
name = "libgcrypt_sys"
path = "lib.rs"

[features]
default = ["v1_7_0"]
shim = []
v1_6_0 = []
v1_7_0 = ["v1_6_0"]

[build-dependencies]
cfg-if = "0.1"
gcc = "0.3"

[dependencies]
libc = "0.2"
libgpg-error-sys = "0.2"
